name: API Pipeline 
on:
  pull_request:
    branches: [main, qa, demo]
    paths: 
      - 'api/**'
      - '.github/workflows/api-ci.yml'

  push: 
    branches: [main, qa, demo]
    paths: 
      - 'api/**'
      - '.github/workflows/api-ci.yml'

jobs:
  lint-and-typecheck:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest 
    
    defaults:
      run: 
        working-directory: api

    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v5 
      
      - name: Set up Python with cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      # Install only linting tools
      - name: Install linting tools
        run: |
          pip install --upgrade pip
          pip install flake8 black isort

      # Run linters 
      - name: Run flake8
        continue-on-error: true
        run: flake8 . --count --max-complexity=10 --max-line-length=88 --statistics
      
      - name: Check code formatting (black)
        continue-on-error: true
        run: black --check --diff .
      
      - name: Check import sorting (isort)
        continue-on-error: true
        run: isort --check-only --diff .

  push-image:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/demo')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: Login to Amazon ECR 
        id: login-ecr 
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: misp-workbench-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f api/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG api
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
