name: Terraform Pipeline 
on:
  pull_request:
    branch: [main, qa, dev]
    paths:
      - 'deployment/terraform/**'
  
  push:
    branch: [main, qa, dev]
    paths:
      - 'deployment/terraform/**'