name: Terraform Pipeline 
on:
  pull_request:
    branch: [main, qa, dev]
    paths:
      - 'deployment/terraform/**'
  
  push:
    branch: [main, qa, dev]
    paths:
      - 'deployment/terraform/**'

jobs:
  terraform-lint: 
    runs-on: ubuntu-latest 
    defaults:
      run: 
        working-directory: deployment
    
    steps:
      - uses: actions/checkout@v5
      - name: Install Terraform lint 
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Using tflint 
        run: 
  terraform-plan:
  terraform-deploy: